<?php
require_once('head.php');
require_once('contents.php');
/*require_once('header.php');
require_once('socmed.php');
require_once('menu-bar.php');
require_once('slider.php');
require_once('contents.php');*/
require_once('footer.php');